name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            solr-version: 7
            solr-package-version: 7.7.3
            solr-sha512: ca9200c18cc19ab723fd4d10f257e27eb81dc8bc33401ebc4eb99178faf4033a2684f0f8b12ae7b659cfeb0f4c9d9e24aaac518a4e00fd28b69854a359a666ed
            solr-keys: CFCE5FBB920C3C745CEEE084C38FF5EC3FCFDB3E
          -
            solr-version: 8
            solr-package-version: 8.11.1
            solr-sha512: 4893f836aec84b03d7bfe574e59e305c03b5ede4a48020034fbe81440b8feee79e55fd9ead230e5b89b3f25124e9b56c1ddc4bb5c7f631cf4e846b9cab5f9a45
            solr-keys: 2CECBFBA181601547B654B9FFA81AC8A490F538E
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ${{ matrix.solr-version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            SOLR_VERSION=${{ matrix.solr-package-version }}
            SOLR_SHA512=${{ matrix.solr-sha512 }}
            SOLR_KEYS=${{ matrix.solr-keys }}
          push: true
          tags: aerzas/solr:${{ matrix.solr-version }}-latest,aerzas/solr:${{ matrix.solr-version }}-${{ github.ref_name }}
