name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            solr-version: 9
            solr-package: solr/solr
            solr-package-version: 9.5.0
            solr-sha512: e34b2421db8586691ff41b86beca77bcb61243ce8edfade74eda8da4b0fabde0078884db301350a0d0dfc4a6fee46320ddf059469300444da4e3693220df5e40
            solr-keys: E05FDF113D89E7FB4A2DF4B2684D544160392455
            solr-download-server: https://www.apache.org/dyn/closer.lua?action=download&filename=/solr/solr
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ${{ matrix.solr-version }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            SOLR_PACKAGE=${{ matrix.solr-package }}
            SOLR_VERSION=${{ matrix.solr-package-version }}
            SOLR_SHA512=${{ matrix.solr-sha512 }}
            SOLR_KEYS=${{ matrix.solr-keys }}
            SOLR_DOWNLOAD_SERVER=${{ matrix.solr-download-server }}
          push: true
          tags: aerzas/solr:${{ matrix.solr-version }}-latest,aerzas/solr:${{ matrix.solr-version }}-${{ github.ref_name }}
