name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            solr-version: 9
            solr-package: solr/solr
            solr-package-version: 9.6.1
            solr-sha512: 7e16aa71fc01f9d9b05e5514e35798104a18253a211426aa669aa3b91225d110a4fa1c78c9ec86b7e1909e2aae63696deffd877536790303cd0638eb7f1a8c63
            solr-keys: 50E3EE1C91C7E0CB4DFB007B369424FC98F3F6EC
            solr-download-server: https://www.apache.org/dyn/closer.lua?action=download&filename=/solr/solr
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ${{ matrix.solr-version }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            SOLR_PACKAGE=${{ matrix.solr-package }}
            SOLR_VERSION=${{ matrix.solr-package-version }}
            SOLR_SHA512=${{ matrix.solr-sha512 }}
            SOLR_KEYS=${{ matrix.solr-keys }}
            SOLR_DOWNLOAD_SERVER=${{ matrix.solr-download-server }}
          push: true
          tags: aerzas/solr:${{ matrix.solr-version }}-latest,aerzas/solr:${{ matrix.solr-version }}-${{ github.ref_name }}
